Guia10/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//para usar "DataAnnotations"
using System.ComponentModel.DataAnnotations; 

namespace Guia10.Models
{
    public class Doctor
    {
        //agregar propiedades -> campos
        [Key]
        [Display(Name ="Codigo Doctor")]
        [Required(ErrorMessage ="El codigo es obligatorio")]
        [StringLength(6, MinimumLength = 6, ErrorMessage= "El codigo debe tener 6 Caracteres")]

        public string CodigoDoctor { get; set; }
        [Display(Name = "No. DUI")]
        [Required(ErrorMessage = "El DUI es obligatorio")]
        [StringLength(10, MinimumLength = 10, ErrorMessage = "El DUi debe  tener 10 Caracteres")]
        public string DUI { get; set; }
        
        [Required(ErrorMessage = "Los nombres son obligatorios")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Los Nombres deben tener entre 3 y 50 Caracteres")]
        public string Nombres { get; set; }
        [Required(ErrorMessage = "Los apellidos son obligatorios")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "Los Apellidos deben tener entre 3 y 50 Caracteres")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "La Especialidad es  obligatorio")]
        [StringLength(20, MinimumLength = 5, ErrorMessage = "La especialidad debe tener entre 5 y 20 Caracteres")]
        public string Especialidad { get; set; }
        [Required(ErrorMessage = "El cargo es  obligatorio")]
        [StringLength(50, MinimumLength = 3, ErrorMessage = "El Cargo debe tener entre 5 y 20 Caracteres")]
        public string Cargo { get; set; }
        

    }
}

Guia10/Controllers/DoctorsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Core.Mapping;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Guia10.Data;
using Guia10.Models;

namespace Guia10.Controllers
{
    public class DoctorsController : Controller
    {
        private Guia10Context db = new Guia10Context();

        // GET: Doctors
        //agregar parametro para realizar ordenamiento 
        public ActionResult Index(string sortOrder)
        {
            //parametro de ordenamiento en el campo"Apellidos"
            //lo enviamos a la vista
            ViewBag.ApellidoSortParam = String.IsNullOrEmpty(sortOrder) ? "apellido_desc" : "";

            // parametro de ordenamiento en el campo"Apellidos"
            //lo enviamos a la vista
            ViewBag.DUISortParam = sortOrder == "dui_asc" ? "dui_desc" : "dui_asc";

            //variable para lista de doctores de acuerdo al ordenamiento
            //usamos LINQ
            var doctores = from s in db.Doctors select s; 
            switch(sortOrder)
            {
                //ordenamiento descendente por campo "Apellidos" 
                case "apellido_desc":
                    doctores = doctores.OrderByDescending(s => s.Apellidos); 
                    break;

                //ordenamiento descendente por campo "DUI" 
                case "dui_desc":
                    doctores = doctores.OrderByDescending(s => s.DUI);
                    break;

                //ordenamiento ascendente por campo "DUI" 
                case "dui_asc":
                    doctores = doctores.OrderBy(s => s.DUI);
                    break;

                //ordenamiento descendente por campo "Apellidos" 
                default:
                    doctores = doctores.OrderBy(s => s.Apellidos);
                    break;
            }
            return View(doctores.ToList());
            //return View(db.Doctors.ToList());
        }

        // GET: Doctors/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // GET: Doctors/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Doctors/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CodigoDoctor,DUI,Nombres,Apellidos,Especialidad,Cargo")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Doctors.Add(doctor);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(doctor);
        }

        // GET: Doctors/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CodigoDoctor,DUI,Nombres,Apellidos,Especialidad,Cargo")] Doctor doctor)
        {
            if (ModelState.IsValid)
            {
                db.Entry(doctor).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(doctor);
        }

        // GET: Doctors/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Doctor doctor = db.Doctors.Find(id);
            if (doctor == null)
            {
                return HttpNotFound();
            }
            return View(doctor);
        }

        // POST: Doctors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Doctor doctor = db.Doctors.Find(id);
            db.Doctors.Remove(doctor);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Guia10/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Guia10.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Sistema de Gestion de clinica.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Pagina de Informacion.";

            return View();
        }
    }
}

Guia10/Views/Doctors/Create.cshtml
@model Guia10.Models.Doctor

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CodigoDoctor, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CodigoDoctor, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CodigoDoctor, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DUI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DUI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DUI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Especialidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Especialidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Especialidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar doctor" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Guia10/Views/Doctors/Delete.cshtml
@model Guia10.Models.Doctor

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DUI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DUI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Guia10/Views/Doctors/Details.cshtml
@model Guia10.Models.Doctor

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DUI)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DUI)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellidos)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Especialidad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cargo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cargo)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CodigoDoctor }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Guia10/Views/Doctors/Edit.cshtml
@model Guia10.Models.Doctor

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Doctor</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CodigoDoctor)

        <div class="form-group">
            @Html.LabelFor(model => model.DUI, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DUI, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DUI, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellidos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellidos, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellidos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Especialidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Especialidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Especialidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cargo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cargo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cargo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Guia10/Views/Doctors/Index.cshtml
@model IEnumerable<Guia10.Models.Doctor>

@{
    ViewBag.Title = "Index";
}

<h2>Listado de Doctores</h2>

<p>
    @Html.ActionLink("Agregar Nuevo", "Create")
</p>
<table class="table">
    <tr>
        <!--
    <th>
        @Html.DisplayNameFor(model => model.DUI)
    </th>-->
        <th>
            @Html.ActionLink("DUI", "Index", new { sortOrder = ViewBag.DUISortParam })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <!--
    <th>
        @Html.DisplayNameFor(model => model.Apellidos)
    </th>-->
        <th>
            @Html.ActionLink("Apellidos", "Index", new { sortOrder = ViewBag.ApellidoSortParam })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Especialidad)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cargo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DUI)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Apellidos)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Especialidad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cargo)
        </td>
        <td>
            @Html.ActionLink("Modificar", "Edit", new { id=item.CodigoDoctor }) |
            @Html.ActionLink("Detalles", "Details", new { id=item.CodigoDoctor }) |
            @Html.ActionLink("Eliminar", "Delete", new { id=item.CodigoDoctor })
        </td>
    </tr>
}

</table>

Guia10/Views/Home/About.cshtml
@{
    ViewBag.Title = "Acerca de...";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>&copy; Derechos Reservados- "Clinica Buena Vida"</p>
</main>

Guia10/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contacto";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        Clinica "Buena Vida"<br />
        San  Salvador, El Salvador<br />
        <abbr title="Phone">Telefono:</abbr>
        2121-2221
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:clinicaBuenaVida@gmail.com">clinicaBuenaVida@gmail.com</a><br />
       
    </address>
</main>

Guia10/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Pagina Principal ";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">Sistema de Gestion de Clinica </h1>
        <p class="lead">Este sistema informatico para el control de las actividades de la clinica Buena Vida.</p>
     
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Bienvenido al Sistema de Gestion de Clinica</h2>
            <p>
                Este sistema informatico es una aplicacion simple que demuestra como
                se utiliza "Entity Framework" en una aplicacion Web ASP:NET MVC.
              
            </p>
          
        </section>
        <!--
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>-->
    </div>
</main>

Guia10/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sistema de Gestion de Clinica</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Sistema de Gestion de Clinica", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Doctores", "Index", "Doctors", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Pacientes", "Index", "Pacientes", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Citas", "Index", "Citas", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sistema de Gestion de Clinica</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>